version: '3.7'
services:

  # ngrok:
  #   image: wernight/ngrok
  #   container_name: ocean_nutrition_ngrok
  #   ports:
  #     - 4040:4040
  #   links:
  #     - app
  #   environment:
  #     - NGROK_PROTOCOL=http
  #     - NGROK_PORT=app:5000
  #     - NGROK_AUTH=${NGROK_AUTH}

  app:
    container_name: ocean_nutrition_app_5000
    image: lambci/lambda:build-python3.7
    ports:
      - 5001:5001
    env_file: ./config/.env.local
    volumes:
      - .:/srv
    working_dir: /srv
    command: sh -c "pip install -r src/requirements.txt && pip install toml && pip install src/. && flask run"
